import { useState } from 'react';
import { router } from 'expo-router';
import { Platform, Pressable, StyleSheet, Text, View } from 'react-native';
import type { DiscoveredAdapter } from '@prius/obd-core';
import { connectBluetoothAdapter, scanBluetoothAdapters } from '../src/connection';
import { requestBluetoothPermissions } from '../src/bluetooth-permissions';
import { Button } from '../src/components/Controls';
import { Card, Screen, Subtitle, Title } from '../src/components/Screen';
import { colors } from '../src/theme';

export default function BluetoothSetup() {
  const [mode, setMode] = useState<'BLE' | 'ANDROID_CLASSIC'>('BLE'); const [adapters, setAdapters] = useState<DiscoveredAdapter[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const scan = async () => { setBusy(true); setError(''); setAdapters([]); try { await requestBluetoothPermissions(mode); setAdapters(await scanBluetoothAdapters(mode)); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } finally { setBusy(false); } };
  const connect = async (adapter: DiscoveredAdapter) => { setBusy(true); setError(''); try { await connectBluetoothAdapter(adapter); router.replace('/dashboard'); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } finally { setBusy(false); } };
  return <Screen><Title>Bluetooth OBD</Title><Subtitle>Turn on the vehicle, insert the ELM327 adapter, and keep the phone close during setup.</Subtitle>{Platform.OS === 'android' ? <View style={styles.modeRow}><Pressable onPress={() => setMode('BLE')} style={[styles.mode, mode === 'BLE' && styles.activeMode]}><Text style={styles.modeText}>BLE</Text></Pressable><Pressable onPress={() => setMode('ANDROID_CLASSIC')} style={[styles.mode, mode === 'ANDROID_CLASSIC' && styles.activeMode]}><Text style={styles.modeText}>Classic paired</Text></Pressable></View> : <Card><Text style={styles.info}>iPhone supports BLE adapters here. Generic Bluetooth Classic SPP adapters are not supported by iOS.</Text></Card>}<Button disabled={busy} onPress={() => void scan()}>{busy ? 'Working...' : 'Scan nearby adapters'}</Button>{error ? <Text accessibilityRole="alert" style={styles.error}>{error}</Text> : null}{!busy && !error && !adapters.length ? <Text style={styles.empty}>No scan results yet.</Text> : null}{adapters.map((adapter) => <Pressable accessibilityRole="button" key={adapter.id} disabled={busy} onPress={() => void connect(adapter)}><Card><View style={styles.adapterRow}><View style={styles.nameArea}><Text style={styles.name}>{adapter.name}</Text><Text numberOfLines={1} style={styles.id}>{adapter.id}</Text></View><Text style={styles.signal}>{adapter.signalStrength === undefined ? 'Paired' : `${adapter.signalStrength} dBm`}</Text></View><Text style={styles.connect}>Tap to connect and initialize ELM327</Text></Card></Pressable>)}</Screen>;
}
const styles = StyleSheet.create({ modeRow: { flexDirection: 'row', gap: 10 }, mode: { flex: 1, padding: 14, alignItems: 'center', borderRadius: 12, backgroundColor: colors.raised, borderWidth: 1, borderColor: colors.border }, activeMode: { borderColor: colors.accent, backgroundColor: colors.surface }, modeText: { color: colors.text, fontWeight: '800' }, info: { color: colors.muted, lineHeight: 22 }, error: { color: colors.warning, lineHeight: 22 }, empty: { color: colors.unavailable, textAlign: 'center' }, adapterRow: { flexDirection: 'row', justifyContent: 'space-between', gap: 12 }, nameArea: { flex: 1 }, name: { color: colors.text, fontSize: 19, fontWeight: '800' }, id: { color: colors.unavailable, fontSize: 12 }, signal: { color: colors.accent, fontWeight: '700' }, connect: { color: colors.muted } });
