import { useKeepAwake } from 'expo-keep-awake';
import { router } from 'expo-router';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Card, Screen, Title } from '../src/components/Screen';
import { useConnectionStore, useSettingsStore, useTelemetryStore, useTripStore } from '../src/stores/app';
import { colors } from '../src/theme';

const Value = ({ id, label, fallback = '--' }: { id: string; label: string; fallback?: string }) => { const sample = useTelemetryStore((s) => s.values[id]); return <Card style={styles.valueCard}><Text style={styles.label}>{label}</Text><Text accessibilityLabel={`${label}: ${sample?.value ?? 'unavailable'} ${sample?.unit ?? ''}`} style={[styles.value, (!sample || sample.quality !== 'VALID') && styles.unavailable]}>{sample ? `${typeof sample.value === 'number' ? Math.round(sample.value * 10) / 10 : sample.value}` : fallback}</Text><Text style={styles.unit}>{sample?.unit ?? 'Unavailable'}</Text></Card>; };
const KeepAwake = () => { useKeepAwake(); return null; };

export default function Dashboard() {
  const keepAwake = useSettingsStore((s) => s.keepAwake); const connection = useConnectionStore(); const trip = useTripStore((s) => s.active);
  return <Screen>{keepAwake ? <KeepAwake /> : null}<View style={styles.header}><Title>Simple drive</Title><View><Text style={styles.connected}>* {connection.status}</Text><Text style={styles.latency}>{connection.latencyMs ?? '--'} ms</Text></View></View><View style={styles.grid}><Value id="speed" label="Speed" /><Value id="rpm" label="Engine" /><Value id="coolantTemperature" label="Coolant" /><Value id="fuelRate" label="Fuel rate" /></View><Card><Text style={styles.label}>Trip average</Text><Text style={styles.tripAverage}>{trip?.averageLitresPer100Km === null || !trip ? 'Calculating...' : `${trip.averageLitresPer100Km.toFixed(1)} L/100 km`}</Text><Text style={styles.unit}>{trip ? `${trip.distanceKm.toFixed(2)} km / ${Math.round(trip.durationSeconds / 60)} min` : 'Starts automatically when the vehicle moves'}</Text></Card><Card><Text style={styles.label}>Hybrid battery</Text><Text style={styles.unverified}>Not available - Toyota command is unverified</Text></Card><View style={styles.nav}>{[['Battery','/battery'],['Trips','/trips'],['Diagnostics','/diagnostics'],['Settings','/settings']].map(([label, path]) => <Pressable key={label} onPress={() => router.push(path as never)} style={styles.navButton}><Text style={styles.navText}>{label}</Text></Pressable>)}</View></Screen>;
}
const styles = StyleSheet.create({ header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, connected: { color: colors.normal, fontWeight: '800' }, latency: { color: colors.muted, textAlign: 'right' }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 }, valueCard: { width: '48%', minHeight: 145 }, label: { color: colors.muted, fontSize: 15, fontWeight: '700', textTransform: 'uppercase' }, value: { color: colors.text, fontSize: 46, fontWeight: '900' }, tripAverage: { color: colors.text, fontSize: 30, fontWeight: '900' }, unit: { color: colors.muted, fontSize: 15 }, unavailable: { color: colors.unavailable }, unverified: { color: colors.unavailable, fontSize: 18 }, nav: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 }, navButton: { backgroundColor: colors.raised, borderRadius: 12, padding: 14 }, navText: { color: colors.text, fontWeight: '700' } });
